name: workflow1
on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: echo "Hello"
      - name: step2
        run: echo "Bye"
      - name: step3
        run: python3 file.py 
